The tutorial can be found 
[here:](https://www.tensorflow.org/tutorials/quickstart/beginner)

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2025-08-18 15:58:31.861257: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1755554311.922980   23544 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1755554311.941540   23544 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-08-18 15:58:32.070908: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.18.0


In [2]:
import tensorflow as tf

devices = tf.config.list_physical_devices()
for device in devices:
    print(device)


PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')
PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


In [3]:
import tensorflow as tf
print("GPU Available: ", len(tf.config.list_physical_devices('GPU')) > 0)

GPU Available:  True


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/home/maxkaizo/miniconda3/envs/conda_tf_gpu311/lib/python3.11/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
I0000 00:00:1755554318.712185   23544 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3539 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.02913637, -0.10030326, -0.4448401 ,  0.26124388,  0.54517764,
        -0.4356952 ,  0.25167635, -0.12578076, -0.08643244, -0.11114791]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.1006878 , 0.08846306, 0.06268036, 0.12699303, 0.16869053,
        0.06325619, 0.1257838 , 0.08623771, 0.08969866, 0.08750888]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.7605624)

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=10)

2025-08-18 15:58:41.842955: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.
2025-08-18 15:58:43.848890: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/10


I0000 00:00:1755554325.055022   23597 service.cc:148] XLA service 0x762ce8003770 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1755554325.055244   23597 service.cc:156]   StreamExecutor device (0): NVIDIA GeForce RTX 4050 Laptop GPU, Compute Capability 8.9
2025-08-18 15:58:45.131128: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1755554325.281435   23597 cuda_dnn.cc:529] Loaded cuDNN version 90300


  28/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.3558 - loss: 2.0052

I0000 00:00:1755554325.875788   23597 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.8604 - loss: 0.4867
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9554 - loss: 0.1512
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9672 - loss: 0.1069
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9737 - loss: 0.0846
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.9775 - loss: 0.0725
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9800 - loss: 0.0612
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9833 - loss: 0.0541
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9829 - loss: 0.0516
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9851 - loss: 0.0470
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9864 - loss: 0.0417


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

2025-08-18 16:00:03.409325: I external/local_xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:397] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_34', 4 bytes spill stores, 4 bytes spill loads



313/313 - 3s - 8ms/step - accuracy: 0.9786 - loss: 0.0698


[0.06977282464504242, 0.978600025177002]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.14241105e-08, 9.95425076e-10, 2.43083446e-06, 9.52514310e-05,
        5.94502366e-13, 2.29385434e-11, 2.59117252e-16, 9.99901533e-01,
        1.35263152e-08, 7.12261510e-07],
       [1.09128717e-09, 5.73764788e-04, 9.99426246e-01, 1.29245326e-08,
        1.92318274e-24, 5.15648801e-10, 2.28757951e-14, 6.96300046e-16,
        3.90235518e-11, 8.19053596e-16],
       [1.02738245e-08, 9.99914885e-01, 5.03394949e-06, 2.25689529e-08,
        4.09811946e-07, 2.31389663e-07, 5.08825266e-08, 7.72174099e-05,
        2.10052849e-06, 3.80566245e-10],
       [9.99985456e-01, 6.70889108e-11, 1.27179101e-05, 1.72272130e-09,
        1.75289921e-10, 9.90697004e-07, 3.07487539e-07, 6.01034600e-08,
        1.47935364e-09, 4.96949497e-07],
       [1.83049133e-06, 9.51304031e-13, 2.85092710e-06, 2.39121678e-09,
        9.96568680e-01, 5.54062915e-12, 4.30490275e-08, 6.73853947e-06,
        7.86573306e-10, 3.41986027e-03]], dtype=float32)>

In [15]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
  loss='sparse_categorical_crossentropy',
  metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

2025-08-18 16:01:18.918772: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.
2025-08-18 16:01:19.959808: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.8575 - loss: 0.4823
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9538 - loss: 0.1556
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9657 - loss: 0.1119
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9730 - loss: 0.0879
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9767 - loss: 0.0743
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9714 - loss: 0.0923


[0.07728377729654312, 0.9764000177383423]